# 스위프트린트 기본 설정 파일
disabled_rules: # 비활성화할 규칙 목록
  - trailing_whitespace # 줄 끝 공백 허용

opt_in_rules: # 선택 규칙 활성화
  - empty_count # count() 대신 isEmpty 사용 권장
  - explicit_init # 명시적 초기화 권장
  - force_unwrapping # 강제 언래핑

included: # 린트가 실행될 파일/폴더
  - iOS_Wegg/ # 프로젝트 폴더
excluded: # 린트에서 제외할 파일/폴더
  # - Pods/ # CocoaPods를 사용하는 경우
  - Carthage/
  - iOS_Wegg/GeneratedFiles/
  - "*.generated.swift" # 자동 생성된 Swift 파일 제외

force_cast:
  severity: error # 강제 캐스팅 금지

force_unwrapping:
  severity: error # 강제 언래핑 금지

line_length:
  # warning: 90 # 라인 길이 경고
  error: 100   # 라인 길이 에러
  ignores_comments: true  # 주석은 길이 제한에서 제외
  ignores_interpolated_strings: false  # 문자열 보간은 검사

type_name:
  min_length: # 타입 이름 최소 길이
    warning: 3
    error: 2
  max_length: # 타입 이름 최대 길이
    warning: 40
    error: 50

function_body_length:
  warning: 40 # 함수 본문 경고 길이
  error: 100  # 함수 본문 에러 길이

file_length:
  warning: 400 # 파일 길이 경고
  error: 1000  # 파일 길이 에러

vertical_whitespace:
  max_empty_lines: 1

identifier_name:
  min_length: # 식별자(변수명, 함수명 등) 최소 길이
    warning: 3
    error: 2
  max_length: # 식별자 이름 최대 길이
    warning: 40
    error: 50

custom_rules: # 사용자 정의 규칙
  todo_or_fixme: # TODO, FIXME 관련 규칙
    name: "TODO or FIXME rule"
    regex: "(TODO|FIXME)"
    message: "TODO와 FIXME는 반드시 처리해야 합니다."
    severity: warning